dist: trusty

sudo: false

language: ruby

cache:
  - bundler

matrix:
  include:
    - rvm: 2.4.1
      jdk: openjdk8

env:
  - ES_VERSION=5.3.1 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz

install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &

after_success:
  - bundle exec codeclimate-test-reporter
